### PR TITLE
'host' config no longer suported, use 'hosts' instead.

### PR DESCRIPTION
**Pull request by larmog**
Minor fix ;)

### CODE REVIEW

**Comment by pires** [comment]
Should we replace the FQDN - which includes namespace and cluster domain - for the service name alone,`elasticsearch`?

**Comment by larmog** [comment]
Yes, of course, my mistake.
I had dns trouble, I couldn't look up services without the namespace for some reason.

**Comment by pires** [comment]
Care to try and let me know?

**Comment by larmog** [comment]
Hi, sorry for the delay. I've verified that it works:

```
$ kubectl get secret logstash.conf -o json | conf2kube -x
input {
  lumberjack {
    port => 5043
    ssl_certificate => "/logstash/certs/logstash.crt"
    ssl_key => "/logstash/certs/logstash.key"
    type => "lumberjack"
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
  }
}
```

and the logstash-forwarder log:

```
2016/03/11 15:13:41.575130 Registrar: processing 1024 events
2016/03/11 15:13:55.862568 Registrar: processing 1024 events
2016/03/11 15:14:01.671923 Registrar: processing 1024 events
2016/03/11 15:14:02.889663 Registrar: processing 256 events
```

and Kibana:

```
2016-03-11T15:17:56.101799650Z {"type":"log","@timestamp":"2016-03-11T15:17:56+00:00","tags":["status","plugin:elasticsearch","info"],"pid":7,"name":"plugin:elasticsearch","state":"green","message":"Status changed from yellow to green - Kibana index ready","prevState":"yellow","prevMsg":"No existing Kibana index found"}
```

Ok?

**Comment by pires** [comment]
OK. Change and update the PR then. Squash your commits.

**Comment by larmog** [comment]
Ok, done!

**Comment by pires** [comment]
Why did you remove `cluster` setting? Is it no longer supported?

**Comment by larmog** [comment]
I'm no expert but according to [doc](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html) there's no longer a `cluster` config and `http` is the only supported protocol. `port` is specified in the `hosts` config.
/Regards

**Comment by pires** [comment]
Nevermind, thank you.

**Comment by azimut** [comment]
I think the current pires/logstash image on the public registry does not support this change. If possible please push an update. Thanks.

**Comment by pires** [comment]
@azimut please open an issue in said repo. I'm no longer using Logstash so I'm not sure if I can pick it up anytime soon.

**Pull request merged**
